# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1104, 918)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainLabel = QtWidgets.QLabel(self.centralwidget)
        self.mainLabel.setGeometry(QtCore.QRect(410, 0, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.mainLabel.setFont(font)
        self.mainLabel.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.mainLabel.setObjectName("mainLabel")
        self.newTaskLabel = QtWidgets.QLabel(self.centralwidget)
        self.newTaskLabel.setGeometry(QtCore.QRect(30, 60, 221, 61))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(20)
        self.newTaskLabel.setFont(font)
        self.newTaskLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.newTaskLabel.setObjectName("newTaskLabel")
        self.clickHereButton = QtWidgets.QPushButton(self.centralwidget)
        self.clickHereButton.setGeometry(QtCore.QRect(270, 80, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.clickHereButton.setFont(font)
        self.clickHereButton.setObjectName("clickHereButton")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(26, 133, 1061, 741))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.remainingLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.remainingLabel.setFont(font)
        self.remainingLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.remainingLabel.setObjectName("remainingLabel")
        self.verticalLayout.addWidget(self.remainingLabel)
        self.RemainingList = QtWidgets.QListWidget(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(14)
        self.RemainingList.setFont(font)
        self.RemainingList.setObjectName("RemainingList")
        self.verticalLayout.addWidget(self.RemainingList)
        self.finishButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.finishButton.setFont(font)
        self.finishButton.setTabletTracking(True)
        self.finishButton.setObjectName("finishButton")
        self.verticalLayout.addWidget(self.finishButton)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.notDoneButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.notDoneButton.setFont(font)
        self.notDoneButton.setObjectName("notDoneButton")
        self.verticalLayout_2.addWidget(self.notDoneButton)
        self.deleteButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.deleteButton.setFont(font)
        self.deleteButton.setObjectName("deleteButton")
        self.verticalLayout_2.addWidget(self.deleteButton)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.finishedLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(20)
        self.finishedLabel.setFont(font)
        self.finishedLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.finishedLabel.setObjectName("finishedLabel")
        self.verticalLayout_3.addWidget(self.finishedLabel)
        self.finishedList = QtWidgets.QListWidget(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(14)
        self.finishedList.setFont(font)
        self.finishedList.setObjectName("finishedList")
        self.verticalLayout_3.addWidget(self.finishedList)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.cleraAllButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cleraAllButton.setFont(font)
        self.cleraAllButton.setObjectName("cleraAllButton")
        self.verticalLayout_4.addWidget(self.cleraAllButton)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1104, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addSeparator()
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.mainLabel.setText(_translate("MainWindow", "TODO Application"))
        self.newTaskLabel.setText(_translate("MainWindow", "To add new task"))
        self.clickHereButton.setText(_translate("MainWindow", "Click Here"))
        self.remainingLabel.setText(_translate("MainWindow", "Remaining Task"))
        self.finishButton.setText(_translate("MainWindow", "Finished"))
        self.notDoneButton.setText(_translate("MainWindow", "Not Done"))
        self.deleteButton.setText(_translate("MainWindow", "Delete Task"))
        self.finishedLabel.setText(_translate("MainWindow", "Finished Task"))
        self.cleraAllButton.setText(_translate("MainWindow", "Clear All"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionLoad.setText(_translate("MainWindow", "Load"))
        self.actionNew.setText(_translate("MainWindow", "New "))

