# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Todo_Application.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1014, 725)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(390, 30, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.saveButton.setFont(font)
        self.saveButton.setObjectName("saveButton")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 90, 961, 581))
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.remainingLabel = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.remainingLabel.setFont(font)
        self.remainingLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.remainingLabel.setObjectName("remainingLabel")
        self.verticalLayout_2.addWidget(self.remainingLabel)
        self.RemainingList = QtWidgets.QListWidget(self.widget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(14)
        self.RemainingList.setFont(font)
        self.RemainingList.setObjectName("RemainingList")
        self.verticalLayout_2.addWidget(self.RemainingList)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.deleteButton = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.deleteButton.setFont(font)
        self.deleteButton.setObjectName("deleteButton")
        self.horizontalLayout_2.addWidget(self.deleteButton)
        self.editButton = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.editButton.setFont(font)
        self.editButton.setObjectName("editButton")
        self.horizontalLayout_2.addWidget(self.editButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.finishButton = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.finishButton.setFont(font)
        self.finishButton.setTabletTracking(True)
        self.finishButton.setObjectName("finishButton")
        self.verticalLayout_2.addWidget(self.finishButton)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.finishedLabel = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(20)
        self.finishedLabel.setFont(font)
        self.finishedLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.finishedLabel.setObjectName("finishedLabel")
        self.verticalLayout_3.addWidget(self.finishedLabel)
        self.finishedList = QtWidgets.QListWidget(self.widget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(14)
        self.finishedList.setFont(font)
        self.finishedList.setObjectName("finishedList")
        self.verticalLayout_3.addWidget(self.finishedList)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.notDoneButton = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.notDoneButton.setFont(font)
        self.notDoneButton.setObjectName("notDoneButton")
        self.horizontalLayout.addWidget(self.notDoneButton)
        self.cleraAllButton = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cleraAllButton.setFont(font)
        self.cleraAllButton.setObjectName("cleraAllButton")
        self.horizontalLayout.addWidget(self.cleraAllButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(30, 10, 341, 71))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.newTaskLabel = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(20)
        self.newTaskLabel.setFont(font)
        self.newTaskLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.newTaskLabel.setObjectName("newTaskLabel")
        self.horizontalLayout_3.addWidget(self.newTaskLabel)
        self.clickHereButton = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.clickHereButton.setFont(font)
        self.clickHereButton.setObjectName("clickHereButton")
        self.horizontalLayout_3.addWidget(self.clickHereButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TODO Application"))
        self.saveButton.setText(_translate("MainWindow", "Save Tasks"))
        self.remainingLabel.setText(_translate("MainWindow", "TODO Task List"))
        self.deleteButton.setText(_translate("MainWindow", "Delete Task"))
        self.editButton.setText(_translate("MainWindow", "Edit Task"))
        self.finishButton.setText(_translate("MainWindow", "Finished"))
        self.finishedLabel.setText(_translate("MainWindow", "Finished Task"))
        self.notDoneButton.setText(_translate("MainWindow", "Not Done"))
        self.cleraAllButton.setText(_translate("MainWindow", "Clear All"))
        self.newTaskLabel.setText(_translate("MainWindow", "To add new task"))
        self.clickHereButton.setText(_translate("MainWindow", "Click Here"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionNew.setText(_translate("MainWindow", "New "))

